#server:
#  port: 8443
#  ssl:
#    key-store-password: tumama
#    key-store: file:/Users/fescalona/keystore.p12
#    key-store-type: PKCS12
#    key-alias: ferhttps

#logging:
#  level:
#    org:
#      springframework: debug
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
